version: 2

builds:
  - id: ctk
    main: ./cmd/main.go
    binary: ctk
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - binary
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
